" Setup Powerline
set rtp+=$HOME/.local/lib/python2.7/site-packages/powerline/bindings/vim/
" Always show statusline
set laststatus=2

set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab

set relativenumber
set nowrap
set smartindent
set autoindent

set backspace=eol,start,indent

set nocompatible
filetype off

set rtp+=~/.vim/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'scrooloose/nerdtree'
Plugin 'chriskempson/base16-vim'
Plugin 'ctrlpvim/ctrlp.vim'
call vundle#end()

filetype plugin indent on

" Configure YCM
let g:ycm_global_ycm_extra_conf = "~/.vim/.ycm_extra_conf.py"

" Configure NERDTree
nnoremap <C-k><C-b> :NERDTreeToggle<CR>
nnoremap <C-k><C-f> :NERDTreeFocus<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Set colourscheme
set t_Co=256
let base16colorspace=256
set background=dark
colorscheme base16-chalk

