filetype plugin indent on

" Always show statusline
set laststatus=2

set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab

set colorcolumn=80

set relativenumber
set nowrap
set smartindent
set autoindent

set cursorline

set backspace=eol,start,indent

set nocompatible
syntax on

call plug#begin('~/.vim/plugged')
Plug 'Valloric/YouCompleteMe', { 'do': 'install.py --clang-completer --system-libclang' }
Plug 'scrooloose/nerdtree'
Plug 'chriskempson/base16-vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'benmills/vimux'
Plug 'junegunn/limelight.vim'
Plug 'junegunn/goyo.vim'
Plug 'majutsushi/tagbar'
call plug#end()

" Configure YCM
let g:ycm_global_ycm_extra_conf = "~/.vim/.ycm_extra_conf.py"
let g:ycm_python_binary_path = "python"

" Configure NERDTree
nnoremap <C-k><C-b> :NERDTreeToggle<CR>
nnoremap <C-k><C-f> :NERDTreeFocus<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Set colourscheme
set t_Co=256
let base16colorspace=256
set background=dark
colorscheme base16-chalk

let g:VimuxRunnerType="pane"
nnoremap <F5> :call VimuxRunCommand("m")<CR>
nnoremap <F6> :call VimuxRunCommand("mt")<CR>

map <C-K> :py3f /usr/share/clang/clang-format.py<CR>
imap <C-k><C-o> :py3f /usr/share/clang/clang-format.py<CR>

set listchars=tab:»·,nbsp:·,trail:·,extends:→,precedes:←,eol:¬
set list

" Setup distraction free writing
function! s:goyo_enter()
	silent !tmux set status off
	silent !tmux list-panes -F '\#F' | grep -q Z || tmux resize-pane -Z
	set noshowmode
	set noshowcmd
	set scrolloff=999
	Limelight
endfunction

function! s:goyo_leave()
	silent !tmux set status on
	silent !tmux list-panes -F '\#F' | grep -q Z && tmux resize-pane -Z
	set showmode
	set showcmd
	set scrolloff=5
	Limelight!
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()
nnoremap <F11> :Goyo<CR>
