#!/bin/bash

if [[ -d /etc/X11/xinit/xinitrc.d ]] ; then
	for file in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[[ -x "${file}" ]] && source "${file}"
	done
	unset "${file}"
fi

source ${HOME}/.xprofile

exec dwm
