#!/bin/bash

if [[ -d /etc/X11/xinit/xinitrc.d ]] ; then
	for file in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[[ -x "${file}" ]] && source "${file}"
	done
	unset "${file}"
fi

xrdb -merge ~/.Xresources

xautolock -time 5 -locker "~/bin/lock ~/Pictures/mario.png" &

xsetroot -solid "#151515"

urxvtd -q -f -o

exec i3
