#!/usr/bin/env bash

case $1 in
	start)
		tmux new-session -d -s temp
		tmux run-shell /home/${USER}/.tmux/plugins/tmux-resurrect/scripts/restore.sh
		tmux kill-session -t temp
	;;

	stop)
		tmux run-shell /home/${USER}/.tmux/plugins/tmux-resurrect/scripts/save.sh
		tmux kill-server
	;;
esac

exit 0
