#!/bin/bash

alias xephyr='Xephyr -ac -br -noreset -screen 800x600 :1'

alias cmake='cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON'

alias ls='ls --color=auto'
alias ll='ls -lisah'

alias tmux="tmux -f ${XDG_CONFIG_HOME}/tmux/tmux.conf"
