#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

source /usr/share/bash-completion/bash_completion

source ~/.bash_aliases

if [ "${TERM%%-*}" == "linux" ]; then
    source "${XDG_CONFIG_HOME}/tty/themes/nord.sh"

    ## Set the font size to something more palettable
    setfont "${XDG_DATA_HOME}/share/fonts/ter-powerline-v12n.psf.gz"
else
	source $XDG_CONFIG_HOME/bash/themes/nord.sh
fi

colour_scheme_nord

export PS1="\\$ "

export GPG_TTY=$(tty)

export TIGRC_USER="${XDG_CONFIG_HOME}/tigrc"

